[package]
name = "esdt-faucet-sc-meta"
version = "0.4.0"
authors = ["Julian Ćwirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[dependencies.esdt-faucet-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.5"
