[package]
name = "esdt-faucet-sc-meta"
version = "0.5.0"
authors = ["Julian Ćwirko <julian.io>"]
edition = "2021"
publish = false

[dependencies.esdt-faucet-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.5"
